apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: retail-store
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: retail-store-consumer:latest
          envFrom:
            - configMapRef:
                name: retail-store-config
            - secretRef:
                name: retail-store-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
