apiVersion: v1
kind: Secret
metadata:
  name: retail-store-secret
  namespace: retail-store
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "changeme"
  REDIS_PASSWORD: ""
  ELASTICSEARCH_USERNAME: ""
  ELASTICSEARCH_PASSWORD: ""
